export const MAX_RETRIES_HIT = "MAX_RETRIES_HIT";
export const USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS";
export const EMPTY_USER_NAME = "EMPTY_USER_NAME";
export const GENERIC_ERROR = "GENERIC_ERROR";
